index.html
static/css/style.css
templates/template.html

I have added colours and styled the nav bar and footer relevant to fonts and colour palette

Add Footer info and Styled Nav/Footer and amended pages

---

404.html
index.html
templates/template.html
thankyou.html

Fixes stylesheet link so that stylesheet is found when site is deployed to Github pages

Fixes stylesheet link for deploy to work

---

script.js
search.html

The feature allows users to search for mentors based on their roles. Currently only implemented 'hiring manager' and 'software developer', further roles and search options are to be added upon discussion with the team. Code needs to be further documented, which will be done as the feature continues to be expanded.
Related GitHub Issue:
https://github.com/users/Jade-ux/projects/3?pane=issue&itemId=23145531

Feature: All users to search through mentors by their role

---

404.html
index.html
search.html
templates/template.html
thankyou.html

- Stary closing body tag deleted `</body>`
- Placed classes in the class attribute `<div row p-3>` ->  `<div class="row p-3">`
- Moved the `<nav>` and `<footer>` to be in the `<body> `element
- Replaced the `<container>` element with a `<div>` that had the 'container' class

Fixed validation on all HTML pages

---

signup.html
static/css/style.css

created signup page and add its layout.

feat: add signup page

---

static/css/style.css

#32 Have amended colours, add hover styling and tidied up the look of the site

Colour accessibility

---

script.js
search.html

- Variables renamed to be more universal - to work with future changes.
- Docstrings added to explain function usage
- Function has been broken into smaller sub-functions, allowing re-usability.

Clean up JavaScript search function

---

search.html

The mentor images have now been updated to use the images saved on the repo, rather than making HTTP requests to external sites. This should increase overall site performance.

Use the new images for the mentor cards

---

signup.html
static/css/style.css

add media query for mobile so the footer changes to flex-direction column and include text-center class.

fix: edit footer to flex column on mobile

---

inspiration.html

Change classes to make it work properly on mobile.

fix: edit layout to work on mobile

---

search.html

Wrapped each card in separate divs with classes to improve responsivity by limiting the maximum height of each.

Add classes to fix card max height.

---

templates/template.html

Replaced .fixed-bottom class in the footer with .footer class for a better UX experience.

Change fixed-bottom with footer class in template.

---

script.js

Previously the hide and show functionality was based on children of the 'cards' class. Now it will hide and show the parent of the card, which will work with the changes to the DOM layout of the search.html file.

fix: javascript search to work with new columns

---

static/css/style.css
templates/404.html
templates/thankyou.html

I can't resolve the scrolling issue on the 404 page caused by the animation elements

thank you page content and styling and work on 404 animation

---

static/js/script.js
templates/search.html

- Add new tags such as skills and career progression to the JS search function
- Currently this will not be exclusive (meaning that if both 'Dublin' and 'Software Developer' are clicked then it will show all mentors that are either in Dublin or a Software Developer, I will discuss with the team if they believe this should be exclusive)

feat: add new categories to search functionality

---

templates/signup.html

As we spoke on Slack, I changed current status to areas of interest and added to the list:
Full-stack development
Front-end development
Back-end development
Dev ops
Added current role.

feat: add new inputs for the form

---

templates/search.html

All mentor cards have now been added to the page. Once the reset button has been created I will return to clean up all of the cards (full stops and alphabetize the checkboxes)

feat: add the final three mentor cards to search page

---

templates/search.html

- Add alt tags to mentor card images
- Alphabetize the checkboxes
- Add full stops to all descriptions
- A lot of HTML validation errors on search.html

fix: clean up mentor page and validation

---

templates/contact.html

Add further name content to the mentor search form.

Add name content to mentor form.

---

app.py
static/css/style.css
templates/booking.html
templates/contact.html
templates/signup.html

Added the thank you for contact page.

feat: add thank you page for contact
